name: NamelessMC
main: com.namelessmc.namelessplugin.NamelessPlugin
author: Samerton
version: 0.1
commands:
  register:
    description: Register for an account on the website
    usage: /register email
softdepend: [Vault]
